apiVersion: v1
kind: Deployment
metadata:
  name: webnode
spec:
  selector:
    matchLabels:
      app: webnode
  template:
    metadata:
      labels:
        app: webnode
    spec:
      containers:
      - name: webnode
        image: ellisonalencar/conversao-temperatura:v1
        ports:
         - containerPort: 8080
---
#service
apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  selector:
    app: webservice
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort

